// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/talos/v2alpha1/talos.proto

package talosv2alpha1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApiKeys_AdminIssueApiKey_FullMethodName                = "/talos.v2alpha1.ApiKeys/AdminIssueApiKey"
	ApiKeys_AdminGetIssuedApiKey_FullMethodName            = "/talos.v2alpha1.ApiKeys/AdminGetIssuedApiKey"
	ApiKeys_AdminListIssuedApiKeys_FullMethodName          = "/talos.v2alpha1.ApiKeys/AdminListIssuedApiKeys"
	ApiKeys_AdminUpdateIssuedApiKey_FullMethodName         = "/talos.v2alpha1.ApiKeys/AdminUpdateIssuedApiKey"
	ApiKeys_AdminRotateIssuedApiKey_FullMethodName         = "/talos.v2alpha1.ApiKeys/AdminRotateIssuedApiKey"
	ApiKeys_AdminRevokeIssuedApiKey_FullMethodName         = "/talos.v2alpha1.ApiKeys/AdminRevokeIssuedApiKey"
	ApiKeys_AdminImportApiKey_FullMethodName               = "/talos.v2alpha1.ApiKeys/AdminImportApiKey"
	ApiKeys_AdminBatchCreateImportedApiKeys_FullMethodName = "/talos.v2alpha1.ApiKeys/AdminBatchCreateImportedApiKeys"
	ApiKeys_AdminUpdateImportedApiKey_FullMethodName       = "/talos.v2alpha1.ApiKeys/AdminUpdateImportedApiKey"
	ApiKeys_AdminGetImportedApiKey_FullMethodName          = "/talos.v2alpha1.ApiKeys/AdminGetImportedApiKey"
	ApiKeys_AdminListImportedApiKeys_FullMethodName        = "/talos.v2alpha1.ApiKeys/AdminListImportedApiKeys"
	ApiKeys_AdminDeleteImportedApiKey_FullMethodName       = "/talos.v2alpha1.ApiKeys/AdminDeleteImportedApiKey"
	ApiKeys_AdminRevokeImportedApiKey_FullMethodName       = "/talos.v2alpha1.ApiKeys/AdminRevokeImportedApiKey"
	ApiKeys_RevokeApiKey_FullMethodName                    = "/talos.v2alpha1.ApiKeys/RevokeApiKey"
	ApiKeys_AdminDeriveToken_FullMethodName                = "/talos.v2alpha1.ApiKeys/AdminDeriveToken"
	ApiKeys_GetJwks_FullMethodName                         = "/talos.v2alpha1.ApiKeys/GetJwks"
	ApiKeys_AdminVerifyApiKey_FullMethodName               = "/talos.v2alpha1.ApiKeys/AdminVerifyApiKey"
	ApiKeys_AdminBatchVerifyApiKeys_FullMethodName         = "/talos.v2alpha1.ApiKeys/AdminBatchVerifyApiKeys"
)

// ApiKeysClient is the client API for ApiKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # ApiKeys - Manages API key lifecycle and verification
//
// The ApiKeys service provides administrative operations for managing API keys.
// Deploy behind appropriate authentication and authorization.
//
// Key features:
// - API key lifecycle management (issue, verify, revoke, rotate, import)
// - Issued key management (keys generated by Talos)
// - Imported key management (keys from external systems)
// - Token derivation and minting (JWT and Macaroon)
// - API key verification (single and batch)
// - JWKS endpoint for public key distribution
type ApiKeysClient interface {
	// Issue API Key
	//
	// Creates a new API key for a given actor. The secret is returned only once
	// in the response and cannot be retrieved later. Keys can be scoped with
	// specific permissions and have optional expiration.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys
	//
	//	{
	//	  "name": "production-service",
	//	  "actor_id": "user_123",
	//	  "scopes": ["read", "write"],
	//	  "ttl": "8760h"
	//	}
	//
	// ```
	AdminIssueApiKey(ctx context.Context, in *IssueApiKeyRequest, opts ...grpc.CallOption) (*IssueApiKeyResponse, error)
	// Get Issued API Key
	//
	// Retrieves details about a specific issued API key including its status,
	// scopes, expiration, and usage statistics. The secret is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ
	// ```
	AdminGetIssuedApiKey(ctx context.Context, in *GetIssuedApiKeyRequest, opts ...grpc.CallOption) (*IssuedApiKey, error)
	// List Issued API Keys
	//
	// Lists issued API keys with optional filtering. Supports cursor-based
	// pagination and AIP-160 filter expressions. Returns only issued
	// (generated) API keys; use ListImportedApiKeys for imported keys.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys?page_size=50&filter=actor_id%3D%22user_123%22
	// ```
	AdminListIssuedApiKeys(ctx context.Context, in *ListIssuedApiKeysRequest, opts ...grpc.CallOption) (*ListIssuedApiKeysResponse, error)
	// Update Issued API Key
	//
	// Updates metadata, scopes, or rate limits of an issued key without rotating
	// the secret. Use RotateIssuedApiKey to change the secret.
	//
	// Follows AIP-134: the request body is the IssuedApiKey resource itself,
	// and the update_mask query parameter names the subset of fields to apply.
	// Omitting update_mask is equivalent to a mask of every populated field
	// in the body. To clear a field to its zero value, list it explicitly in
	// update_mask and leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ?update_mask=scopes
	//
	//	{
	//	  "issued_api_key": {
	//	    "key_id": "01HQZX9VYQKJB8XQZQXQZQXQXQ",
	//	    "scopes": ["read"]
	//	  }
	//	}
	//
	// ```
	AdminUpdateIssuedApiKey(ctx context.Context, in *UpdateIssuedApiKeyRequest, opts ...grpc.CallOption) (*IssuedApiKey, error)
	// Rotate Issued API Key
	//
	// Generates a new secret for an issued API key. Creates a new API key with a
	// new key_id and secret, and immediately revokes the old key. This is the
	// recommended way to update scopes, metadata, or rotate credentials.
	//
	// For zero-downtime rotation, use this workflow instead:
	//  1. IssueApiKey with new credentials
	//  2. Deploy new secret to all services
	//  3. Verify new secret works everywhere
	//  4. AdminRevokeIssuedApiKey to remove the old key
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:rotate
	//
	//	{
	//	  "scopes": ["read"]
	//	}
	//
	// ```
	AdminRotateIssuedApiKey(ctx context.Context, in *RotateIssuedApiKeyRequest, opts ...grpc.CallOption) (*RotateIssuedApiKeyResponse, error)
	// Revoke Issued API Key
	//
	// Immediately revokes an issued API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeIssuedApiKey(ctx context.Context, in *RevokeIssuedApiKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Import API Key
	//
	// Imports an external API key into the system. Allows importing keys from
	// legacy systems or external providers. The raw key is hashed and stored
	// securely (HMAC). Imported keys support token derivation (JWT/Macaroon)
	// like issued keys.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys
	//
	//	{
	//	  "raw_key": "sk_live_abc123xyz",
	//	  "name": "Imported Stripe Key",
	//	  "actor_id": "user_123"
	//	}
	//
	// ```
	AdminImportApiKey(ctx context.Context, in *ImportApiKeyRequest, opts ...grpc.CallOption) (*ImportedApiKey, error)
	// Batch Import API Keys
	//
	// Imports up to 1000 external API keys in one request. Returns per-item
	// results. If at least one item succeeds, response is 200 OK. If all items
	// fail, the endpoint returns a non-200 error.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys:batchCreate
	//
	//	{
	//	  "requests": [
	//	    {"raw_key": "sk_live_abc", "name": "Stripe key", "actor_id": "user_1"},
	//	    {"raw_key": "ghp_xyz", "name": "GitHub PAT", "actor_id": "user_2"}
	//	  ]
	//	}
	//
	// ```
	AdminBatchCreateImportedApiKeys(ctx context.Context, in *BatchCreateImportedApiKeysRequest, opts ...grpc.CallOption) (*BatchCreateImportedApiKeysResponse, error)
	// Update Imported API Key
	//
	// Updates metadata, scopes, or rate limits of an imported key. Supports
	// partial updates via the update_mask query parameter (AIP-134). Omitting
	// update_mask is equivalent to a mask of every populated field in the body.
	// To clear a field to its zero value, list it explicitly in update_mask and
	// leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/importedApiKeys/{key_id}?update_mask=name
	//
	//	{
	//	  "imported_api_key": {
	//	    "key_id": "{key_id}",
	//	    "name": "New name"
	//	  }
	//	}
	//
	// ```
	AdminUpdateImportedApiKey(ctx context.Context, in *UpdateImportedApiKeyRequest, opts ...grpc.CallOption) (*ImportedApiKey, error)
	// Get Imported API Key
	//
	// Retrieves details about a specific imported key. Returns metadata about
	// the imported key. The original raw key is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminGetImportedApiKey(ctx context.Context, in *GetImportedApiKeyRequest, opts ...grpc.CallOption) (*ImportedApiKey, error)
	// List Imported API Keys
	//
	// Lists all imported keys with filtering. Returns imported keys only (not
	// issued keys). Supports pagination and AIP-160 filter expressions.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys?page_size=50&filter=status%3DKEY_STATUS_ACTIVE
	// ```
	AdminListImportedApiKeys(ctx context.Context, in *ListImportedApiKeysRequest, opts ...grpc.CallOption) (*ListImportedApiKeysResponse, error)
	// Delete Imported API Key
	//
	// Permanently deletes an imported key (hard delete). The key is removed from
	// the database. Use AdminRevokeImportedApiKey for soft deletion (recommended).
	//
	// ```http
	// DELETE /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminDeleteImportedApiKey(ctx context.Context, in *DeleteImportedApiKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Revoke Imported API Key
	//
	// Immediately revokes an imported API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys/9a3f051b2c7e8d4f1a6b9c0e5f2d8a3b:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeImportedApiKey(ctx context.Context, in *RevokeImportedApiKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Revoke API Key (self-service)
	//
	// Proof-of-possession variant of revocation. The `Self*` prefix on the
	// request/response messages disambiguates from the admin variants
	// (`AdminRevokeIssuedApiKey` / `AdminRevokeImportedApiKey`).
	//
	// Allows an API key holder to revoke their own key. The caller must provide
	// the full API key secret as proof of possession. Supports issued API keys
	// and imported keys. JWT and macaroon tokens cannot be self-revoked (they
	// are stateless).
	//
	// The PRIVILEGE_WITHDRAWN reason is not allowed for self-revocation
	// (admin-only).
	//
	// ```http
	// POST /v2alpha1/apiKeys:selfRevoke
	//
	//	{
	//	  "credential": "sk_live_abc123...",
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	RevokeApiKey(ctx context.Context, in *SelfRevokeApiKeyRequest, opts ...grpc.CallOption) (*SelfRevokeApiKeyResponse, error)
	// Derive Token
	//
	// Mints a short-lived JWT or Macaroon token from an API key. Works with both
	// issued and imported keys. The derived token inherits the permissions of the
	// parent API key.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:derive
	//
	//	{
	//	  "credential": "eyJhbGciOiJFZERTQSI...",
	//	  "ttl": "1h"
	//	}
	//
	// ```
	AdminDeriveToken(ctx context.Context, in *DeriveTokenRequest, opts ...grpc.CallOption) (*DeriveTokenResponse, error)
	// Get JWKS
	//
	// Returns the JSON Web Key Set for token verification. Provides the public
	// keys needed to verify JWT tokens issued by this service. Keys are loaded
	// from configuration (file://, https://, or base64:// URIs). Follows the
	// JWKS standard (RFC 7517).
	//
	// ```http
	// GET /v2alpha1/derivedKeys/jwks.json
	// ```
	GetJwks(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error)
	// Verify API Key
	//
	// Verifies a single API key or derived token. Validates the credential's
	// signature, expiration, and revocation status. Works with any credential
	// type (issued keys, imported keys, JWT, macaroon). The verification result
	// includes decoded claims and metadata — admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:verify
	//
	//	{
	//	  "credential": "sk_live_abc123..."
	//	}
	//
	// ```
	AdminVerifyApiKey(ctx context.Context, in *VerifyApiKeyRequest, opts ...grpc.CallOption) (*VerifyApiKeyResponse, error)
	// Batch Verify API Keys
	//
	// Verifies multiple credentials in a single request. Efficiently verifies up
	// to 100 credentials in parallel. Each credential is verified independently;
	// partial failures are returned. Admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// The cache directive applies to every credential in the batch.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:batchVerify
	//
	//	{
	//	  "requests": [
	//	    {"credential": "sk_live_abc123..."},
	//	    {"credential": "eyJhbGciOiJFZERTQSI..."}
	//	  ]
	//	}
	//
	// ```
	AdminBatchVerifyApiKeys(ctx context.Context, in *BatchVerifyApiKeysRequest, opts ...grpc.CallOption) (*BatchVerifyApiKeysResponse, error)
}

type apiKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewApiKeysClient(cc grpc.ClientConnInterface) ApiKeysClient {
	return &apiKeysClient{cc}
}

func (c *apiKeysClient) AdminIssueApiKey(ctx context.Context, in *IssueApiKeyRequest, opts ...grpc.CallOption) (*IssueApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueApiKeyResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminIssueApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminGetIssuedApiKey(ctx context.Context, in *GetIssuedApiKeyRequest, opts ...grpc.CallOption) (*IssuedApiKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuedApiKey)
	err := c.cc.Invoke(ctx, ApiKeys_AdminGetIssuedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminListIssuedApiKeys(ctx context.Context, in *ListIssuedApiKeysRequest, opts ...grpc.CallOption) (*ListIssuedApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssuedApiKeysResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminListIssuedApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminUpdateIssuedApiKey(ctx context.Context, in *UpdateIssuedApiKeyRequest, opts ...grpc.CallOption) (*IssuedApiKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuedApiKey)
	err := c.cc.Invoke(ctx, ApiKeys_AdminUpdateIssuedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminRotateIssuedApiKey(ctx context.Context, in *RotateIssuedApiKeyRequest, opts ...grpc.CallOption) (*RotateIssuedApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateIssuedApiKeyResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminRotateIssuedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminRevokeIssuedApiKey(ctx context.Context, in *RevokeIssuedApiKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiKeys_AdminRevokeIssuedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminImportApiKey(ctx context.Context, in *ImportApiKeyRequest, opts ...grpc.CallOption) (*ImportedApiKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportedApiKey)
	err := c.cc.Invoke(ctx, ApiKeys_AdminImportApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminBatchCreateImportedApiKeys(ctx context.Context, in *BatchCreateImportedApiKeysRequest, opts ...grpc.CallOption) (*BatchCreateImportedApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateImportedApiKeysResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminBatchCreateImportedApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminUpdateImportedApiKey(ctx context.Context, in *UpdateImportedApiKeyRequest, opts ...grpc.CallOption) (*ImportedApiKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportedApiKey)
	err := c.cc.Invoke(ctx, ApiKeys_AdminUpdateImportedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminGetImportedApiKey(ctx context.Context, in *GetImportedApiKeyRequest, opts ...grpc.CallOption) (*ImportedApiKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportedApiKey)
	err := c.cc.Invoke(ctx, ApiKeys_AdminGetImportedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminListImportedApiKeys(ctx context.Context, in *ListImportedApiKeysRequest, opts ...grpc.CallOption) (*ListImportedApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImportedApiKeysResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminListImportedApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminDeleteImportedApiKey(ctx context.Context, in *DeleteImportedApiKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiKeys_AdminDeleteImportedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminRevokeImportedApiKey(ctx context.Context, in *RevokeImportedApiKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ApiKeys_AdminRevokeImportedApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) RevokeApiKey(ctx context.Context, in *SelfRevokeApiKeyRequest, opts ...grpc.CallOption) (*SelfRevokeApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfRevokeApiKeyResponse)
	err := c.cc.Invoke(ctx, ApiKeys_RevokeApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminDeriveToken(ctx context.Context, in *DeriveTokenRequest, opts ...grpc.CallOption) (*DeriveTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeriveTokenResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminDeriveToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) GetJwks(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJWKSResponse)
	err := c.cc.Invoke(ctx, ApiKeys_GetJwks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminVerifyApiKey(ctx context.Context, in *VerifyApiKeyRequest, opts ...grpc.CallOption) (*VerifyApiKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyApiKeyResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminVerifyApiKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiKeysClient) AdminBatchVerifyApiKeys(ctx context.Context, in *BatchVerifyApiKeysRequest, opts ...grpc.CallOption) (*BatchVerifyApiKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchVerifyApiKeysResponse)
	err := c.cc.Invoke(ctx, ApiKeys_AdminBatchVerifyApiKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiKeysServer is the server API for ApiKeys service.
// All implementations should embed UnimplementedApiKeysServer
// for forward compatibility.
//
// # ApiKeys - Manages API key lifecycle and verification
//
// The ApiKeys service provides administrative operations for managing API keys.
// Deploy behind appropriate authentication and authorization.
//
// Key features:
// - API key lifecycle management (issue, verify, revoke, rotate, import)
// - Issued key management (keys generated by Talos)
// - Imported key management (keys from external systems)
// - Token derivation and minting (JWT and Macaroon)
// - API key verification (single and batch)
// - JWKS endpoint for public key distribution
type ApiKeysServer interface {
	// Issue API Key
	//
	// Creates a new API key for a given actor. The secret is returned only once
	// in the response and cannot be retrieved later. Keys can be scoped with
	// specific permissions and have optional expiration.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys
	//
	//	{
	//	  "name": "production-service",
	//	  "actor_id": "user_123",
	//	  "scopes": ["read", "write"],
	//	  "ttl": "8760h"
	//	}
	//
	// ```
	AdminIssueApiKey(context.Context, *IssueApiKeyRequest) (*IssueApiKeyResponse, error)
	// Get Issued API Key
	//
	// Retrieves details about a specific issued API key including its status,
	// scopes, expiration, and usage statistics. The secret is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ
	// ```
	AdminGetIssuedApiKey(context.Context, *GetIssuedApiKeyRequest) (*IssuedApiKey, error)
	// List Issued API Keys
	//
	// Lists issued API keys with optional filtering. Supports cursor-based
	// pagination and AIP-160 filter expressions. Returns only issued
	// (generated) API keys; use ListImportedApiKeys for imported keys.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys?page_size=50&filter=actor_id%3D%22user_123%22
	// ```
	AdminListIssuedApiKeys(context.Context, *ListIssuedApiKeysRequest) (*ListIssuedApiKeysResponse, error)
	// Update Issued API Key
	//
	// Updates metadata, scopes, or rate limits of an issued key without rotating
	// the secret. Use RotateIssuedApiKey to change the secret.
	//
	// Follows AIP-134: the request body is the IssuedApiKey resource itself,
	// and the update_mask query parameter names the subset of fields to apply.
	// Omitting update_mask is equivalent to a mask of every populated field
	// in the body. To clear a field to its zero value, list it explicitly in
	// update_mask and leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ?update_mask=scopes
	//
	//	{
	//	  "issued_api_key": {
	//	    "key_id": "01HQZX9VYQKJB8XQZQXQZQXQXQ",
	//	    "scopes": ["read"]
	//	  }
	//	}
	//
	// ```
	AdminUpdateIssuedApiKey(context.Context, *UpdateIssuedApiKeyRequest) (*IssuedApiKey, error)
	// Rotate Issued API Key
	//
	// Generates a new secret for an issued API key. Creates a new API key with a
	// new key_id and secret, and immediately revokes the old key. This is the
	// recommended way to update scopes, metadata, or rotate credentials.
	//
	// For zero-downtime rotation, use this workflow instead:
	//  1. IssueApiKey with new credentials
	//  2. Deploy new secret to all services
	//  3. Verify new secret works everywhere
	//  4. AdminRevokeIssuedApiKey to remove the old key
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:rotate
	//
	//	{
	//	  "scopes": ["read"]
	//	}
	//
	// ```
	AdminRotateIssuedApiKey(context.Context, *RotateIssuedApiKeyRequest) (*RotateIssuedApiKeyResponse, error)
	// Revoke Issued API Key
	//
	// Immediately revokes an issued API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeIssuedApiKey(context.Context, *RevokeIssuedApiKeyRequest) (*emptypb.Empty, error)
	// Import API Key
	//
	// Imports an external API key into the system. Allows importing keys from
	// legacy systems or external providers. The raw key is hashed and stored
	// securely (HMAC). Imported keys support token derivation (JWT/Macaroon)
	// like issued keys.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys
	//
	//	{
	//	  "raw_key": "sk_live_abc123xyz",
	//	  "name": "Imported Stripe Key",
	//	  "actor_id": "user_123"
	//	}
	//
	// ```
	AdminImportApiKey(context.Context, *ImportApiKeyRequest) (*ImportedApiKey, error)
	// Batch Import API Keys
	//
	// Imports up to 1000 external API keys in one request. Returns per-item
	// results. If at least one item succeeds, response is 200 OK. If all items
	// fail, the endpoint returns a non-200 error.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys:batchCreate
	//
	//	{
	//	  "requests": [
	//	    {"raw_key": "sk_live_abc", "name": "Stripe key", "actor_id": "user_1"},
	//	    {"raw_key": "ghp_xyz", "name": "GitHub PAT", "actor_id": "user_2"}
	//	  ]
	//	}
	//
	// ```
	AdminBatchCreateImportedApiKeys(context.Context, *BatchCreateImportedApiKeysRequest) (*BatchCreateImportedApiKeysResponse, error)
	// Update Imported API Key
	//
	// Updates metadata, scopes, or rate limits of an imported key. Supports
	// partial updates via the update_mask query parameter (AIP-134). Omitting
	// update_mask is equivalent to a mask of every populated field in the body.
	// To clear a field to its zero value, list it explicitly in update_mask and
	// leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/importedApiKeys/{key_id}?update_mask=name
	//
	//	{
	//	  "imported_api_key": {
	//	    "key_id": "{key_id}",
	//	    "name": "New name"
	//	  }
	//	}
	//
	// ```
	AdminUpdateImportedApiKey(context.Context, *UpdateImportedApiKeyRequest) (*ImportedApiKey, error)
	// Get Imported API Key
	//
	// Retrieves details about a specific imported key. Returns metadata about
	// the imported key. The original raw key is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminGetImportedApiKey(context.Context, *GetImportedApiKeyRequest) (*ImportedApiKey, error)
	// List Imported API Keys
	//
	// Lists all imported keys with filtering. Returns imported keys only (not
	// issued keys). Supports pagination and AIP-160 filter expressions.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys?page_size=50&filter=status%3DKEY_STATUS_ACTIVE
	// ```
	AdminListImportedApiKeys(context.Context, *ListImportedApiKeysRequest) (*ListImportedApiKeysResponse, error)
	// Delete Imported API Key
	//
	// Permanently deletes an imported key (hard delete). The key is removed from
	// the database. Use AdminRevokeImportedApiKey for soft deletion (recommended).
	//
	// ```http
	// DELETE /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminDeleteImportedApiKey(context.Context, *DeleteImportedApiKeyRequest) (*emptypb.Empty, error)
	// Revoke Imported API Key
	//
	// Immediately revokes an imported API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys/9a3f051b2c7e8d4f1a6b9c0e5f2d8a3b:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeImportedApiKey(context.Context, *RevokeImportedApiKeyRequest) (*emptypb.Empty, error)
	// Revoke API Key (self-service)
	//
	// Proof-of-possession variant of revocation. The `Self*` prefix on the
	// request/response messages disambiguates from the admin variants
	// (`AdminRevokeIssuedApiKey` / `AdminRevokeImportedApiKey`).
	//
	// Allows an API key holder to revoke their own key. The caller must provide
	// the full API key secret as proof of possession. Supports issued API keys
	// and imported keys. JWT and macaroon tokens cannot be self-revoked (they
	// are stateless).
	//
	// The PRIVILEGE_WITHDRAWN reason is not allowed for self-revocation
	// (admin-only).
	//
	// ```http
	// POST /v2alpha1/apiKeys:selfRevoke
	//
	//	{
	//	  "credential": "sk_live_abc123...",
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	RevokeApiKey(context.Context, *SelfRevokeApiKeyRequest) (*SelfRevokeApiKeyResponse, error)
	// Derive Token
	//
	// Mints a short-lived JWT or Macaroon token from an API key. Works with both
	// issued and imported keys. The derived token inherits the permissions of the
	// parent API key.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:derive
	//
	//	{
	//	  "credential": "eyJhbGciOiJFZERTQSI...",
	//	  "ttl": "1h"
	//	}
	//
	// ```
	AdminDeriveToken(context.Context, *DeriveTokenRequest) (*DeriveTokenResponse, error)
	// Get JWKS
	//
	// Returns the JSON Web Key Set for token verification. Provides the public
	// keys needed to verify JWT tokens issued by this service. Keys are loaded
	// from configuration (file://, https://, or base64:// URIs). Follows the
	// JWKS standard (RFC 7517).
	//
	// ```http
	// GET /v2alpha1/derivedKeys/jwks.json
	// ```
	GetJwks(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error)
	// Verify API Key
	//
	// Verifies a single API key or derived token. Validates the credential's
	// signature, expiration, and revocation status. Works with any credential
	// type (issued keys, imported keys, JWT, macaroon). The verification result
	// includes decoded claims and metadata — admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:verify
	//
	//	{
	//	  "credential": "sk_live_abc123..."
	//	}
	//
	// ```
	AdminVerifyApiKey(context.Context, *VerifyApiKeyRequest) (*VerifyApiKeyResponse, error)
	// Batch Verify API Keys
	//
	// Verifies multiple credentials in a single request. Efficiently verifies up
	// to 100 credentials in parallel. Each credential is verified independently;
	// partial failures are returned. Admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// The cache directive applies to every credential in the batch.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:batchVerify
	//
	//	{
	//	  "requests": [
	//	    {"credential": "sk_live_abc123..."},
	//	    {"credential": "eyJhbGciOiJFZERTQSI..."}
	//	  ]
	//	}
	//
	// ```
	AdminBatchVerifyApiKeys(context.Context, *BatchVerifyApiKeysRequest) (*BatchVerifyApiKeysResponse, error)
}

// UnimplementedApiKeysServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApiKeysServer struct{}

func (UnimplementedApiKeysServer) AdminIssueApiKey(context.Context, *IssueApiKeyRequest) (*IssueApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminIssueApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminGetIssuedApiKey(context.Context, *GetIssuedApiKeyRequest) (*IssuedApiKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetIssuedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminListIssuedApiKeys(context.Context, *ListIssuedApiKeysRequest) (*ListIssuedApiKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListIssuedApiKeys not implemented")
}
func (UnimplementedApiKeysServer) AdminUpdateIssuedApiKey(context.Context, *UpdateIssuedApiKeyRequest) (*IssuedApiKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdateIssuedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminRotateIssuedApiKey(context.Context, *RotateIssuedApiKeyRequest) (*RotateIssuedApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRotateIssuedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminRevokeIssuedApiKey(context.Context, *RevokeIssuedApiKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRevokeIssuedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminImportApiKey(context.Context, *ImportApiKeyRequest) (*ImportedApiKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminImportApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminBatchCreateImportedApiKeys(context.Context, *BatchCreateImportedApiKeysRequest) (*BatchCreateImportedApiKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminBatchCreateImportedApiKeys not implemented")
}
func (UnimplementedApiKeysServer) AdminUpdateImportedApiKey(context.Context, *UpdateImportedApiKeyRequest) (*ImportedApiKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdateImportedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminGetImportedApiKey(context.Context, *GetImportedApiKeyRequest) (*ImportedApiKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetImportedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminListImportedApiKeys(context.Context, *ListImportedApiKeysRequest) (*ListImportedApiKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListImportedApiKeys not implemented")
}
func (UnimplementedApiKeysServer) AdminDeleteImportedApiKey(context.Context, *DeleteImportedApiKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeleteImportedApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminRevokeImportedApiKey(context.Context, *RevokeImportedApiKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRevokeImportedApiKey not implemented")
}
func (UnimplementedApiKeysServer) RevokeApiKey(context.Context, *SelfRevokeApiKeyRequest) (*SelfRevokeApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminDeriveToken(context.Context, *DeriveTokenRequest) (*DeriveTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeriveToken not implemented")
}
func (UnimplementedApiKeysServer) GetJwks(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJwks not implemented")
}
func (UnimplementedApiKeysServer) AdminVerifyApiKey(context.Context, *VerifyApiKeyRequest) (*VerifyApiKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminVerifyApiKey not implemented")
}
func (UnimplementedApiKeysServer) AdminBatchVerifyApiKeys(context.Context, *BatchVerifyApiKeysRequest) (*BatchVerifyApiKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminBatchVerifyApiKeys not implemented")
}
func (UnimplementedApiKeysServer) testEmbeddedByValue() {}

// UnsafeApiKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiKeysServer will
// result in compilation errors.
type UnsafeApiKeysServer interface {
	mustEmbedUnimplementedApiKeysServer()
}

func RegisterApiKeysServer(s grpc.ServiceRegistrar, srv ApiKeysServer) {
	// If the following call pancis, it indicates UnimplementedApiKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApiKeys_ServiceDesc, srv)
}

func _ApiKeys_AdminIssueApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminIssueApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminIssueApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminIssueApiKey(ctx, req.(*IssueApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminGetIssuedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssuedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminGetIssuedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminGetIssuedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminGetIssuedApiKey(ctx, req.(*GetIssuedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminListIssuedApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuedApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminListIssuedApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminListIssuedApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminListIssuedApiKeys(ctx, req.(*ListIssuedApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminUpdateIssuedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssuedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminUpdateIssuedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminUpdateIssuedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminUpdateIssuedApiKey(ctx, req.(*UpdateIssuedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminRotateIssuedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateIssuedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminRotateIssuedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminRotateIssuedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminRotateIssuedApiKey(ctx, req.(*RotateIssuedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminRevokeIssuedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeIssuedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminRevokeIssuedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminRevokeIssuedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminRevokeIssuedApiKey(ctx, req.(*RevokeIssuedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminImportApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminImportApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminImportApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminImportApiKey(ctx, req.(*ImportApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminBatchCreateImportedApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateImportedApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminBatchCreateImportedApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminBatchCreateImportedApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminBatchCreateImportedApiKeys(ctx, req.(*BatchCreateImportedApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminUpdateImportedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImportedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminUpdateImportedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminUpdateImportedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminUpdateImportedApiKey(ctx, req.(*UpdateImportedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminGetImportedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminGetImportedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminGetImportedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminGetImportedApiKey(ctx, req.(*GetImportedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminListImportedApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImportedApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminListImportedApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminListImportedApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminListImportedApiKeys(ctx, req.(*ListImportedApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminDeleteImportedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImportedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminDeleteImportedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminDeleteImportedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminDeleteImportedApiKey(ctx, req.(*DeleteImportedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminRevokeImportedApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeImportedApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminRevokeImportedApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminRevokeImportedApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminRevokeImportedApiKey(ctx, req.(*RevokeImportedApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_RevokeApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelfRevokeApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).RevokeApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_RevokeApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).RevokeApiKey(ctx, req.(*SelfRevokeApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminDeriveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminDeriveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminDeriveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminDeriveToken(ctx, req.(*DeriveTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_GetJwks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJWKSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).GetJwks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_GetJwks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).GetJwks(ctx, req.(*GetJWKSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminVerifyApiKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyApiKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminVerifyApiKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminVerifyApiKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminVerifyApiKey(ctx, req.(*VerifyApiKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiKeys_AdminBatchVerifyApiKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchVerifyApiKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiKeysServer).AdminBatchVerifyApiKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiKeys_AdminBatchVerifyApiKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiKeysServer).AdminBatchVerifyApiKeys(ctx, req.(*BatchVerifyApiKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiKeys_ServiceDesc is the grpc.ServiceDesc for ApiKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talos.v2alpha1.ApiKeys",
	HandlerType: (*ApiKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminIssueApiKey",
			Handler:    _ApiKeys_AdminIssueApiKey_Handler,
		},
		{
			MethodName: "AdminGetIssuedApiKey",
			Handler:    _ApiKeys_AdminGetIssuedApiKey_Handler,
		},
		{
			MethodName: "AdminListIssuedApiKeys",
			Handler:    _ApiKeys_AdminListIssuedApiKeys_Handler,
		},
		{
			MethodName: "AdminUpdateIssuedApiKey",
			Handler:    _ApiKeys_AdminUpdateIssuedApiKey_Handler,
		},
		{
			MethodName: "AdminRotateIssuedApiKey",
			Handler:    _ApiKeys_AdminRotateIssuedApiKey_Handler,
		},
		{
			MethodName: "AdminRevokeIssuedApiKey",
			Handler:    _ApiKeys_AdminRevokeIssuedApiKey_Handler,
		},
		{
			MethodName: "AdminImportApiKey",
			Handler:    _ApiKeys_AdminImportApiKey_Handler,
		},
		{
			MethodName: "AdminBatchCreateImportedApiKeys",
			Handler:    _ApiKeys_AdminBatchCreateImportedApiKeys_Handler,
		},
		{
			MethodName: "AdminUpdateImportedApiKey",
			Handler:    _ApiKeys_AdminUpdateImportedApiKey_Handler,
		},
		{
			MethodName: "AdminGetImportedApiKey",
			Handler:    _ApiKeys_AdminGetImportedApiKey_Handler,
		},
		{
			MethodName: "AdminListImportedApiKeys",
			Handler:    _ApiKeys_AdminListImportedApiKeys_Handler,
		},
		{
			MethodName: "AdminDeleteImportedApiKey",
			Handler:    _ApiKeys_AdminDeleteImportedApiKey_Handler,
		},
		{
			MethodName: "AdminRevokeImportedApiKey",
			Handler:    _ApiKeys_AdminRevokeImportedApiKey_Handler,
		},
		{
			MethodName: "RevokeApiKey",
			Handler:    _ApiKeys_RevokeApiKey_Handler,
		},
		{
			MethodName: "AdminDeriveToken",
			Handler:    _ApiKeys_AdminDeriveToken_Handler,
		},
		{
			MethodName: "GetJwks",
			Handler:    _ApiKeys_GetJwks_Handler,
		},
		{
			MethodName: "AdminVerifyApiKey",
			Handler:    _ApiKeys_AdminVerifyApiKey_Handler,
		},
		{
			MethodName: "AdminBatchVerifyApiKeys",
			Handler:    _ApiKeys_AdminBatchVerifyApiKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/talos/v2alpha1/talos.proto",
}
