// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/talos/v2alpha1/talos.proto

package talosv2alpha1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APIKeys_AdminIssueAPIKey_FullMethodName          = "/talos.v2alpha1.APIKeys/AdminIssueAPIKey"
	APIKeys_AdminGetIssuedAPIKey_FullMethodName      = "/talos.v2alpha1.APIKeys/AdminGetIssuedAPIKey"
	APIKeys_AdminListIssuedAPIKeys_FullMethodName    = "/talos.v2alpha1.APIKeys/AdminListIssuedAPIKeys"
	APIKeys_AdminUpdateIssuedAPIKey_FullMethodName   = "/talos.v2alpha1.APIKeys/AdminUpdateIssuedAPIKey"
	APIKeys_AdminRotateIssuedAPIKey_FullMethodName   = "/talos.v2alpha1.APIKeys/AdminRotateIssuedAPIKey"
	APIKeys_AdminRevokeIssuedAPIKey_FullMethodName   = "/talos.v2alpha1.APIKeys/AdminRevokeIssuedAPIKey"
	APIKeys_AdminImportAPIKey_FullMethodName         = "/talos.v2alpha1.APIKeys/AdminImportAPIKey"
	APIKeys_AdminBatchImportAPIKeys_FullMethodName   = "/talos.v2alpha1.APIKeys/AdminBatchImportAPIKeys"
	APIKeys_AdminUpdateImportedAPIKey_FullMethodName = "/talos.v2alpha1.APIKeys/AdminUpdateImportedAPIKey"
	APIKeys_AdminGetImportedAPIKey_FullMethodName    = "/talos.v2alpha1.APIKeys/AdminGetImportedAPIKey"
	APIKeys_AdminListImportedAPIKeys_FullMethodName  = "/talos.v2alpha1.APIKeys/AdminListImportedAPIKeys"
	APIKeys_AdminDeleteImportedAPIKey_FullMethodName = "/talos.v2alpha1.APIKeys/AdminDeleteImportedAPIKey"
	APIKeys_AdminRevokeImportedAPIKey_FullMethodName = "/talos.v2alpha1.APIKeys/AdminRevokeImportedAPIKey"
	APIKeys_RevokeAPIKey_FullMethodName              = "/talos.v2alpha1.APIKeys/RevokeAPIKey"
	APIKeys_AdminDeriveToken_FullMethodName          = "/talos.v2alpha1.APIKeys/AdminDeriveToken"
	APIKeys_GetJWKS_FullMethodName                   = "/talos.v2alpha1.APIKeys/GetJWKS"
	APIKeys_AdminVerifyAPIKey_FullMethodName         = "/talos.v2alpha1.APIKeys/AdminVerifyAPIKey"
	APIKeys_AdminBatchVerifyAPIKeys_FullMethodName   = "/talos.v2alpha1.APIKeys/AdminBatchVerifyAPIKeys"
)

// APIKeysClient is the client API for APIKeys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # APIKeys - Manages API key lifecycle and verification
//
// The APIKeys service provides administrative operations for managing API keys.
// Deploy behind appropriate authentication and authorization.
//
// Key features:
// - API key lifecycle management (issue, verify, revoke, rotate, import)
// - Issued key management (keys generated by Talos)
// - Imported key management (keys from external systems)
// - Token derivation and minting (JWT and Macaroon)
// - API key verification (single and batch)
// - JWKS endpoint for public key distribution
type APIKeysClient interface {
	// Issue API Key
	//
	// Creates a new API key for a given actor. The secret is returned only once
	// in the response and cannot be retrieved later. Keys can be scoped with
	// specific permissions and have optional expiration.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys
	//
	//	{
	//	  "name": "production-service",
	//	  "actor_id": "user_123",
	//	  "scopes": ["read", "write"],
	//	  "ttl": "8760h"
	//	}
	//
	// ```
	AdminIssueAPIKey(ctx context.Context, in *IssueAPIKeyRequest, opts ...grpc.CallOption) (*IssueAPIKeyResponse, error)
	// Get Issued API Key
	//
	// Retrieves details about a specific issued API key including its status,
	// scopes, expiration, and usage statistics. The secret is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ
	// ```
	AdminGetIssuedAPIKey(ctx context.Context, in *GetIssuedAPIKeyRequest, opts ...grpc.CallOption) (*IssuedAPIKey, error)
	// List Issued API Keys
	//
	// Lists issued API keys with optional filtering. Supports cursor-based
	// pagination and AIP-160 filter expressions. Returns only issued
	// (generated) API keys; use ListImportedAPIKeys for imported keys.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys?page_size=50&filter=actor_id%3D%22user_123%22
	// ```
	AdminListIssuedAPIKeys(ctx context.Context, in *ListIssuedAPIKeysRequest, opts ...grpc.CallOption) (*ListIssuedAPIKeysResponse, error)
	// Update Issued API Key
	//
	// Updates metadata, scopes, or rate limits of an issued key without rotating
	// the secret. Use RotateIssuedAPIKey to change the secret.
	//
	// Follows AIP-134: the request body is the IssuedAPIKey resource itself,
	// and the update_mask query parameter names the subset of fields to apply.
	// Omitting update_mask is equivalent to a mask of every populated field
	// in the body. To clear a field to its zero value, list it explicitly in
	// update_mask and leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ?update_mask=scopes
	//
	//	{
	//	  "issued_api_key": {
	//	    "key_id": "01HQZX9VYQKJB8XQZQXQZQXQXQ",
	//	    "scopes": ["read"]
	//	  }
	//	}
	//
	// ```
	AdminUpdateIssuedAPIKey(ctx context.Context, in *UpdateIssuedAPIKeyRequest, opts ...grpc.CallOption) (*IssuedAPIKey, error)
	// Rotate Issued API Key
	//
	// Generates a new secret for an issued API key. Creates a new API key with a
	// new key_id and secret, and immediately revokes the old key. This is the
	// recommended way to update scopes, metadata, or rotate credentials.
	//
	// For zero-downtime rotation, use this workflow instead:
	//  1. IssueAPIKey with new credentials
	//  2. Deploy new secret to all services
	//  3. Verify new secret works everywhere
	//  4. AdminRevokeIssuedAPIKey to remove the old key
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:rotate
	//
	//	{
	//	  "scopes": ["read"]
	//	}
	//
	// ```
	AdminRotateIssuedAPIKey(ctx context.Context, in *RotateIssuedAPIKeyRequest, opts ...grpc.CallOption) (*RotateIssuedAPIKeyResponse, error)
	// Revoke Issued API Key
	//
	// Immediately revokes an issued API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeIssuedAPIKey(ctx context.Context, in *RevokeIssuedAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Import API Key
	//
	// Imports an external API key into the system. Allows importing keys from
	// legacy systems or external providers. The raw key is hashed and stored
	// securely (HMAC). Imported keys support token derivation (JWT/Macaroon)
	// like issued keys.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys
	//
	//	{
	//	  "raw_key": "sk_live_abc123xyz",
	//	  "name": "Imported Stripe Key",
	//	  "actor_id": "user_123"
	//	}
	//
	// ```
	AdminImportAPIKey(ctx context.Context, in *ImportAPIKeyRequest, opts ...grpc.CallOption) (*ImportedAPIKey, error)
	// Batch Import API Keys
	//
	// Imports up to 1000 external API keys in one request. Returns per-item
	// results. If at least one item succeeds, response is 200 OK. If all items
	// fail, the endpoint returns a non-200 error.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys:batchImport
	//
	//	{
	//	  "requests": [
	//	    {"raw_key": "sk_live_abc", "name": "Stripe key", "actor_id": "user_1"},
	//	    {"raw_key": "ghp_xyz", "name": "GitHub PAT", "actor_id": "user_2"}
	//	  ]
	//	}
	//
	// ```
	AdminBatchImportAPIKeys(ctx context.Context, in *BatchImportAPIKeysRequest, opts ...grpc.CallOption) (*BatchImportAPIKeysResponse, error)
	// Update Imported API Key
	//
	// Updates metadata, scopes, or rate limits of an imported key. Supports
	// partial updates via the update_mask query parameter (AIP-134). Omitting
	// update_mask is equivalent to a mask of every populated field in the body.
	// To clear a field to its zero value, list it explicitly in update_mask and
	// leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/importedApiKeys/{key_id}?update_mask=name
	//
	//	{
	//	  "imported_api_key": {
	//	    "key_id": "{key_id}",
	//	    "name": "New name"
	//	  }
	//	}
	//
	// ```
	AdminUpdateImportedAPIKey(ctx context.Context, in *UpdateImportedAPIKeyRequest, opts ...grpc.CallOption) (*ImportedAPIKey, error)
	// Get Imported API Key
	//
	// Retrieves details about a specific imported key. Returns metadata about
	// the imported key. The original raw key is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminGetImportedAPIKey(ctx context.Context, in *GetImportedAPIKeyRequest, opts ...grpc.CallOption) (*ImportedAPIKey, error)
	// List Imported API Keys
	//
	// Lists all imported keys with filtering. Returns imported keys only (not
	// issued keys). Supports pagination and AIP-160 filter expressions.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys?page_size=50&filter=status%3DKEY_STATUS_ACTIVE
	// ```
	AdminListImportedAPIKeys(ctx context.Context, in *ListImportedAPIKeysRequest, opts ...grpc.CallOption) (*ListImportedAPIKeysResponse, error)
	// Delete Imported API Key
	//
	// Permanently deletes an imported key (hard delete). The key is removed from
	// the database. Use AdminRevokeImportedAPIKey for soft deletion (recommended).
	//
	// ```http
	// DELETE /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminDeleteImportedAPIKey(ctx context.Context, in *DeleteImportedAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Revoke Imported API Key
	//
	// Immediately revokes an imported API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys/9a3f051b2c7e8d4f1a6b9c0e5f2d8a3b:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeImportedAPIKey(ctx context.Context, in *RevokeImportedAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Revoke API Key (self-service)
	//
	// Proof-of-possession variant of revocation. The `Self*` prefix on the
	// request/response messages disambiguates from the admin variants
	// (`AdminRevokeIssuedAPIKey` / `AdminRevokeImportedAPIKey`).
	//
	// Allows an API key holder to revoke their own key. The caller must provide
	// the full API key secret as proof of possession. Supports issued API keys
	// and imported keys. JWT and macaroon tokens cannot be self-revoked (they
	// are stateless).
	//
	// The PRIVILEGE_WITHDRAWN reason is not allowed for self-revocation
	// (admin-only).
	//
	// ```http
	// POST /v2alpha1/apiKeys:selfRevoke
	//
	//	{
	//	  "credential": "sk_live_abc123...",
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	RevokeAPIKey(ctx context.Context, in *SelfRevokeAPIKeyRequest, opts ...grpc.CallOption) (*SelfRevokeAPIKeyResponse, error)
	// Derive Token
	//
	// Mints a short-lived JWT or Macaroon token from an API key. Works with both
	// issued and imported keys. The derived token inherits the permissions of the
	// parent API key.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:derive
	//
	//	{
	//	  "credential": "eyJhbGciOiJFZERTQSI...",
	//	  "ttl": "1h"
	//	}
	//
	// ```
	AdminDeriveToken(ctx context.Context, in *DeriveTokenRequest, opts ...grpc.CallOption) (*DeriveTokenResponse, error)
	// Get JWKS
	//
	// Returns the JSON Web Key Set for token verification. Provides the public
	// keys needed to verify JWT tokens issued by this service. Keys are loaded
	// from configuration (file://, https://, or base64:// URIs). Follows the
	// JWKS standard (RFC 7517).
	//
	// ```http
	// GET /v2alpha1/derivedKeys/jwks.json
	// ```
	GetJWKS(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error)
	// Verify API Key
	//
	// Verifies a single API key or derived token. Validates the credential's
	// signature, expiration, and revocation status. Works with any credential
	// type (issued keys, imported keys, JWT, macaroon). The verification result
	// includes decoded claims and metadata — admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:verify
	//
	//	{
	//	  "credential": "sk_live_abc123..."
	//	}
	//
	// ```
	AdminVerifyAPIKey(ctx context.Context, in *VerifyAPIKeyRequest, opts ...grpc.CallOption) (*VerifyAPIKeyResponse, error)
	// Batch Verify API Keys
	//
	// Verifies multiple credentials in a single request. Efficiently verifies up
	// to 100 credentials in parallel. Each credential is verified independently;
	// partial failures are returned. Admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// The cache directive applies to every credential in the batch.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:batchVerify
	//
	//	{
	//	  "requests": [
	//	    {"credential": "sk_live_abc123..."},
	//	    {"credential": "eyJhbGciOiJFZERTQSI..."}
	//	  ]
	//	}
	//
	// ```
	AdminBatchVerifyAPIKeys(ctx context.Context, in *BatchVerifyAPIKeysRequest, opts ...grpc.CallOption) (*BatchVerifyAPIKeysResponse, error)
}

type aPIKeysClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIKeysClient(cc grpc.ClientConnInterface) APIKeysClient {
	return &aPIKeysClient{cc}
}

func (c *aPIKeysClient) AdminIssueAPIKey(ctx context.Context, in *IssueAPIKeyRequest, opts ...grpc.CallOption) (*IssueAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueAPIKeyResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminIssueAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminGetIssuedAPIKey(ctx context.Context, in *GetIssuedAPIKeyRequest, opts ...grpc.CallOption) (*IssuedAPIKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuedAPIKey)
	err := c.cc.Invoke(ctx, APIKeys_AdminGetIssuedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminListIssuedAPIKeys(ctx context.Context, in *ListIssuedAPIKeysRequest, opts ...grpc.CallOption) (*ListIssuedAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIssuedAPIKeysResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminListIssuedAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminUpdateIssuedAPIKey(ctx context.Context, in *UpdateIssuedAPIKeyRequest, opts ...grpc.CallOption) (*IssuedAPIKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuedAPIKey)
	err := c.cc.Invoke(ctx, APIKeys_AdminUpdateIssuedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminRotateIssuedAPIKey(ctx context.Context, in *RotateIssuedAPIKeyRequest, opts ...grpc.CallOption) (*RotateIssuedAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateIssuedAPIKeyResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminRotateIssuedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminRevokeIssuedAPIKey(ctx context.Context, in *RevokeIssuedAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, APIKeys_AdminRevokeIssuedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminImportAPIKey(ctx context.Context, in *ImportAPIKeyRequest, opts ...grpc.CallOption) (*ImportedAPIKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportedAPIKey)
	err := c.cc.Invoke(ctx, APIKeys_AdminImportAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminBatchImportAPIKeys(ctx context.Context, in *BatchImportAPIKeysRequest, opts ...grpc.CallOption) (*BatchImportAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchImportAPIKeysResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminBatchImportAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminUpdateImportedAPIKey(ctx context.Context, in *UpdateImportedAPIKeyRequest, opts ...grpc.CallOption) (*ImportedAPIKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportedAPIKey)
	err := c.cc.Invoke(ctx, APIKeys_AdminUpdateImportedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminGetImportedAPIKey(ctx context.Context, in *GetImportedAPIKeyRequest, opts ...grpc.CallOption) (*ImportedAPIKey, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportedAPIKey)
	err := c.cc.Invoke(ctx, APIKeys_AdminGetImportedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminListImportedAPIKeys(ctx context.Context, in *ListImportedAPIKeysRequest, opts ...grpc.CallOption) (*ListImportedAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImportedAPIKeysResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminListImportedAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminDeleteImportedAPIKey(ctx context.Context, in *DeleteImportedAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, APIKeys_AdminDeleteImportedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminRevokeImportedAPIKey(ctx context.Context, in *RevokeImportedAPIKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, APIKeys_AdminRevokeImportedAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) RevokeAPIKey(ctx context.Context, in *SelfRevokeAPIKeyRequest, opts ...grpc.CallOption) (*SelfRevokeAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfRevokeAPIKeyResponse)
	err := c.cc.Invoke(ctx, APIKeys_RevokeAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminDeriveToken(ctx context.Context, in *DeriveTokenRequest, opts ...grpc.CallOption) (*DeriveTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeriveTokenResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminDeriveToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) GetJWKS(ctx context.Context, in *GetJWKSRequest, opts ...grpc.CallOption) (*GetJWKSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJWKSResponse)
	err := c.cc.Invoke(ctx, APIKeys_GetJWKS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminVerifyAPIKey(ctx context.Context, in *VerifyAPIKeyRequest, opts ...grpc.CallOption) (*VerifyAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAPIKeyResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminVerifyAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeysClient) AdminBatchVerifyAPIKeys(ctx context.Context, in *BatchVerifyAPIKeysRequest, opts ...grpc.CallOption) (*BatchVerifyAPIKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchVerifyAPIKeysResponse)
	err := c.cc.Invoke(ctx, APIKeys_AdminBatchVerifyAPIKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIKeysServer is the server API for APIKeys service.
// All implementations should embed UnimplementedAPIKeysServer
// for forward compatibility.
//
// # APIKeys - Manages API key lifecycle and verification
//
// The APIKeys service provides administrative operations for managing API keys.
// Deploy behind appropriate authentication and authorization.
//
// Key features:
// - API key lifecycle management (issue, verify, revoke, rotate, import)
// - Issued key management (keys generated by Talos)
// - Imported key management (keys from external systems)
// - Token derivation and minting (JWT and Macaroon)
// - API key verification (single and batch)
// - JWKS endpoint for public key distribution
type APIKeysServer interface {
	// Issue API Key
	//
	// Creates a new API key for a given actor. The secret is returned only once
	// in the response and cannot be retrieved later. Keys can be scoped with
	// specific permissions and have optional expiration.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys
	//
	//	{
	//	  "name": "production-service",
	//	  "actor_id": "user_123",
	//	  "scopes": ["read", "write"],
	//	  "ttl": "8760h"
	//	}
	//
	// ```
	AdminIssueAPIKey(context.Context, *IssueAPIKeyRequest) (*IssueAPIKeyResponse, error)
	// Get Issued API Key
	//
	// Retrieves details about a specific issued API key including its status,
	// scopes, expiration, and usage statistics. The secret is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ
	// ```
	AdminGetIssuedAPIKey(context.Context, *GetIssuedAPIKeyRequest) (*IssuedAPIKey, error)
	// List Issued API Keys
	//
	// Lists issued API keys with optional filtering. Supports cursor-based
	// pagination and AIP-160 filter expressions. Returns only issued
	// (generated) API keys; use ListImportedAPIKeys for imported keys.
	//
	// ```http
	// GET /v2alpha1/admin/issuedApiKeys?page_size=50&filter=actor_id%3D%22user_123%22
	// ```
	AdminListIssuedAPIKeys(context.Context, *ListIssuedAPIKeysRequest) (*ListIssuedAPIKeysResponse, error)
	// Update Issued API Key
	//
	// Updates metadata, scopes, or rate limits of an issued key without rotating
	// the secret. Use RotateIssuedAPIKey to change the secret.
	//
	// Follows AIP-134: the request body is the IssuedAPIKey resource itself,
	// and the update_mask query parameter names the subset of fields to apply.
	// Omitting update_mask is equivalent to a mask of every populated field
	// in the body. To clear a field to its zero value, list it explicitly in
	// update_mask and leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ?update_mask=scopes
	//
	//	{
	//	  "issued_api_key": {
	//	    "key_id": "01HQZX9VYQKJB8XQZQXQZQXQXQ",
	//	    "scopes": ["read"]
	//	  }
	//	}
	//
	// ```
	AdminUpdateIssuedAPIKey(context.Context, *UpdateIssuedAPIKeyRequest) (*IssuedAPIKey, error)
	// Rotate Issued API Key
	//
	// Generates a new secret for an issued API key. Creates a new API key with a
	// new key_id and secret, and immediately revokes the old key. This is the
	// recommended way to update scopes, metadata, or rotate credentials.
	//
	// For zero-downtime rotation, use this workflow instead:
	//  1. IssueAPIKey with new credentials
	//  2. Deploy new secret to all services
	//  3. Verify new secret works everywhere
	//  4. AdminRevokeIssuedAPIKey to remove the old key
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:rotate
	//
	//	{
	//	  "scopes": ["read"]
	//	}
	//
	// ```
	AdminRotateIssuedAPIKey(context.Context, *RotateIssuedAPIKeyRequest) (*RotateIssuedAPIKeyResponse, error)
	// Revoke Issued API Key
	//
	// Immediately revokes an issued API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/issuedApiKeys/01HQZX9VYQKJB8XQZQXQZQXQXQ:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeIssuedAPIKey(context.Context, *RevokeIssuedAPIKeyRequest) (*emptypb.Empty, error)
	// Import API Key
	//
	// Imports an external API key into the system. Allows importing keys from
	// legacy systems or external providers. The raw key is hashed and stored
	// securely (HMAC). Imported keys support token derivation (JWT/Macaroon)
	// like issued keys.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys
	//
	//	{
	//	  "raw_key": "sk_live_abc123xyz",
	//	  "name": "Imported Stripe Key",
	//	  "actor_id": "user_123"
	//	}
	//
	// ```
	AdminImportAPIKey(context.Context, *ImportAPIKeyRequest) (*ImportedAPIKey, error)
	// Batch Import API Keys
	//
	// Imports up to 1000 external API keys in one request. Returns per-item
	// results. If at least one item succeeds, response is 200 OK. If all items
	// fail, the endpoint returns a non-200 error.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys:batchImport
	//
	//	{
	//	  "requests": [
	//	    {"raw_key": "sk_live_abc", "name": "Stripe key", "actor_id": "user_1"},
	//	    {"raw_key": "ghp_xyz", "name": "GitHub PAT", "actor_id": "user_2"}
	//	  ]
	//	}
	//
	// ```
	AdminBatchImportAPIKeys(context.Context, *BatchImportAPIKeysRequest) (*BatchImportAPIKeysResponse, error)
	// Update Imported API Key
	//
	// Updates metadata, scopes, or rate limits of an imported key. Supports
	// partial updates via the update_mask query parameter (AIP-134). Omitting
	// update_mask is equivalent to a mask of every populated field in the body.
	// To clear a field to its zero value, list it explicitly in update_mask and
	// leave it unset (or empty) in the body.
	//
	// ```http
	// PATCH /v2alpha1/admin/importedApiKeys/{key_id}?update_mask=name
	//
	//	{
	//	  "imported_api_key": {
	//	    "key_id": "{key_id}",
	//	    "name": "New name"
	//	  }
	//	}
	//
	// ```
	AdminUpdateImportedAPIKey(context.Context, *UpdateImportedAPIKeyRequest) (*ImportedAPIKey, error)
	// Get Imported API Key
	//
	// Retrieves details about a specific imported key. Returns metadata about
	// the imported key. The original raw key is never returned.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminGetImportedAPIKey(context.Context, *GetImportedAPIKeyRequest) (*ImportedAPIKey, error)
	// List Imported API Keys
	//
	// Lists all imported keys with filtering. Returns imported keys only (not
	// issued keys). Supports pagination and AIP-160 filter expressions.
	//
	// ```http
	// GET /v2alpha1/admin/importedApiKeys?page_size=50&filter=status%3DKEY_STATUS_ACTIVE
	// ```
	AdminListImportedAPIKeys(context.Context, *ListImportedAPIKeysRequest) (*ListImportedAPIKeysResponse, error)
	// Delete Imported API Key
	//
	// Permanently deletes an imported key (hard delete). The key is removed from
	// the database. Use AdminRevokeImportedAPIKey for soft deletion (recommended).
	//
	// ```http
	// DELETE /v2alpha1/admin/importedApiKeys/{key_id}
	// ```
	AdminDeleteImportedAPIKey(context.Context, *DeleteImportedAPIKeyRequest) (*emptypb.Empty, error)
	// Revoke Imported API Key
	//
	// Immediately revokes an imported API key. Once revoked, the key can no longer
	// be used for authentication. This operation is irreversible. Revoked keys
	// are retained for audit purposes.
	//
	// ```http
	// POST /v2alpha1/admin/importedApiKeys/9a3f051b2c7e8d4f1a6b9c0e5f2d8a3b:revoke
	//
	//	{
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	AdminRevokeImportedAPIKey(context.Context, *RevokeImportedAPIKeyRequest) (*emptypb.Empty, error)
	// Revoke API Key (self-service)
	//
	// Proof-of-possession variant of revocation. The `Self*` prefix on the
	// request/response messages disambiguates from the admin variants
	// (`AdminRevokeIssuedAPIKey` / `AdminRevokeImportedAPIKey`).
	//
	// Allows an API key holder to revoke their own key. The caller must provide
	// the full API key secret as proof of possession. Supports issued API keys
	// and imported keys. JWT and macaroon tokens cannot be self-revoked (they
	// are stateless).
	//
	// The PRIVILEGE_WITHDRAWN reason is not allowed for self-revocation
	// (admin-only).
	//
	// ```http
	// POST /v2alpha1/apiKeys:selfRevoke
	//
	//	{
	//	  "credential": "sk_live_abc123...",
	//	  "reason": "REVOCATION_REASON_KEY_COMPROMISE"
	//	}
	//
	// ```
	RevokeAPIKey(context.Context, *SelfRevokeAPIKeyRequest) (*SelfRevokeAPIKeyResponse, error)
	// Derive Token
	//
	// Mints a short-lived JWT or Macaroon token from an API key. Works with both
	// issued and imported keys. The derived token inherits the permissions of the
	// parent API key.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:derive
	//
	//	{
	//	  "credential": "eyJhbGciOiJFZERTQSI...",
	//	  "ttl": "1h"
	//	}
	//
	// ```
	AdminDeriveToken(context.Context, *DeriveTokenRequest) (*DeriveTokenResponse, error)
	// Get JWKS
	//
	// Returns the JSON Web Key Set for token verification. Provides the public
	// keys needed to verify JWT tokens issued by this service. Keys are loaded
	// from configuration (file://, https://, or base64:// URIs). Follows the
	// JWKS standard (RFC 7517).
	//
	// ```http
	// GET /v2alpha1/derivedKeys/jwks.json
	// ```
	GetJWKS(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error)
	// Verify API Key
	//
	// Verifies a single API key or derived token. Validates the credential's
	// signature, expiration, and revocation status. Works with any credential
	// type (issued keys, imported keys, JWT, macaroon). The verification result
	// includes decoded claims and metadata — admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:verify
	//
	//	{
	//	  "credential": "sk_live_abc123..."
	//	}
	//
	// ```
	AdminVerifyAPIKey(context.Context, *VerifyAPIKeyRequest) (*VerifyAPIKeyResponse, error)
	// Batch Verify API Keys
	//
	// Verifies multiple credentials in a single request. Efficiently verifies up
	// to 100 credentials in parallel. Each credential is verified independently;
	// partial failures are returned. Admin access only.
	//
	// Cache Control (HTTP Headers):
	//   - Cache-Control: no-cache  - Bypasses cache read, forces fresh DB lookup
	//   - Cache-Control: no-store  - Bypasses cache read AND write (never cached)
	//   - Pragma: no-cache         - Same as Cache-Control: no-cache (HTTP/1.0)
	//
	// The cache directive applies to every credential in the batch.
	//
	// ```http
	// POST /v2alpha1/admin/apiKeys:batchVerify
	//
	//	{
	//	  "requests": [
	//	    {"credential": "sk_live_abc123..."},
	//	    {"credential": "eyJhbGciOiJFZERTQSI..."}
	//	  ]
	//	}
	//
	// ```
	AdminBatchVerifyAPIKeys(context.Context, *BatchVerifyAPIKeysRequest) (*BatchVerifyAPIKeysResponse, error)
}

// UnimplementedAPIKeysServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIKeysServer struct{}

func (UnimplementedAPIKeysServer) AdminIssueAPIKey(context.Context, *IssueAPIKeyRequest) (*IssueAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminIssueAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminGetIssuedAPIKey(context.Context, *GetIssuedAPIKeyRequest) (*IssuedAPIKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetIssuedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminListIssuedAPIKeys(context.Context, *ListIssuedAPIKeysRequest) (*ListIssuedAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListIssuedAPIKeys not implemented")
}
func (UnimplementedAPIKeysServer) AdminUpdateIssuedAPIKey(context.Context, *UpdateIssuedAPIKeyRequest) (*IssuedAPIKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdateIssuedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminRotateIssuedAPIKey(context.Context, *RotateIssuedAPIKeyRequest) (*RotateIssuedAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRotateIssuedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminRevokeIssuedAPIKey(context.Context, *RevokeIssuedAPIKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRevokeIssuedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminImportAPIKey(context.Context, *ImportAPIKeyRequest) (*ImportedAPIKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminImportAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminBatchImportAPIKeys(context.Context, *BatchImportAPIKeysRequest) (*BatchImportAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminBatchImportAPIKeys not implemented")
}
func (UnimplementedAPIKeysServer) AdminUpdateImportedAPIKey(context.Context, *UpdateImportedAPIKeyRequest) (*ImportedAPIKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUpdateImportedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminGetImportedAPIKey(context.Context, *GetImportedAPIKeyRequest) (*ImportedAPIKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetImportedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminListImportedAPIKeys(context.Context, *ListImportedAPIKeysRequest) (*ListImportedAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminListImportedAPIKeys not implemented")
}
func (UnimplementedAPIKeysServer) AdminDeleteImportedAPIKey(context.Context, *DeleteImportedAPIKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeleteImportedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminRevokeImportedAPIKey(context.Context, *RevokeImportedAPIKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRevokeImportedAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) RevokeAPIKey(context.Context, *SelfRevokeAPIKeyRequest) (*SelfRevokeAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminDeriveToken(context.Context, *DeriveTokenRequest) (*DeriveTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminDeriveToken not implemented")
}
func (UnimplementedAPIKeysServer) GetJWKS(context.Context, *GetJWKSRequest) (*GetJWKSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJWKS not implemented")
}
func (UnimplementedAPIKeysServer) AdminVerifyAPIKey(context.Context, *VerifyAPIKeyRequest) (*VerifyAPIKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminVerifyAPIKey not implemented")
}
func (UnimplementedAPIKeysServer) AdminBatchVerifyAPIKeys(context.Context, *BatchVerifyAPIKeysRequest) (*BatchVerifyAPIKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminBatchVerifyAPIKeys not implemented")
}
func (UnimplementedAPIKeysServer) testEmbeddedByValue() {}

// UnsafeAPIKeysServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIKeysServer will
// result in compilation errors.
type UnsafeAPIKeysServer interface {
	mustEmbedUnimplementedAPIKeysServer()
}

func RegisterAPIKeysServer(s grpc.ServiceRegistrar, srv APIKeysServer) {
	// If the following call pancis, it indicates UnimplementedAPIKeysServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIKeys_ServiceDesc, srv)
}

func _APIKeys_AdminIssueAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminIssueAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminIssueAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminIssueAPIKey(ctx, req.(*IssueAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminGetIssuedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIssuedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminGetIssuedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminGetIssuedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminGetIssuedAPIKey(ctx, req.(*GetIssuedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminListIssuedAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIssuedAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminListIssuedAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminListIssuedAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminListIssuedAPIKeys(ctx, req.(*ListIssuedAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminUpdateIssuedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssuedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminUpdateIssuedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminUpdateIssuedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminUpdateIssuedAPIKey(ctx, req.(*UpdateIssuedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminRotateIssuedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateIssuedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminRotateIssuedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminRotateIssuedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminRotateIssuedAPIKey(ctx, req.(*RotateIssuedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminRevokeIssuedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeIssuedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminRevokeIssuedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminRevokeIssuedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminRevokeIssuedAPIKey(ctx, req.(*RevokeIssuedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminImportAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminImportAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminImportAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminImportAPIKey(ctx, req.(*ImportAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminBatchImportAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchImportAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminBatchImportAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminBatchImportAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminBatchImportAPIKeys(ctx, req.(*BatchImportAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminUpdateImportedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImportedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminUpdateImportedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminUpdateImportedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminUpdateImportedAPIKey(ctx, req.(*UpdateImportedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminGetImportedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminGetImportedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminGetImportedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminGetImportedAPIKey(ctx, req.(*GetImportedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminListImportedAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImportedAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminListImportedAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminListImportedAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminListImportedAPIKeys(ctx, req.(*ListImportedAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminDeleteImportedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImportedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminDeleteImportedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminDeleteImportedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminDeleteImportedAPIKey(ctx, req.(*DeleteImportedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminRevokeImportedAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeImportedAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminRevokeImportedAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminRevokeImportedAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminRevokeImportedAPIKey(ctx, req.(*RevokeImportedAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_RevokeAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelfRevokeAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).RevokeAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_RevokeAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).RevokeAPIKey(ctx, req.(*SelfRevokeAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminDeriveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeriveTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminDeriveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminDeriveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminDeriveToken(ctx, req.(*DeriveTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_GetJWKS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJWKSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).GetJWKS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_GetJWKS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).GetJWKS(ctx, req.(*GetJWKSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminVerifyAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminVerifyAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminVerifyAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminVerifyAPIKey(ctx, req.(*VerifyAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeys_AdminBatchVerifyAPIKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchVerifyAPIKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeysServer).AdminBatchVerifyAPIKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeys_AdminBatchVerifyAPIKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeysServer).AdminBatchVerifyAPIKeys(ctx, req.(*BatchVerifyAPIKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIKeys_ServiceDesc is the grpc.ServiceDesc for APIKeys service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIKeys_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talos.v2alpha1.APIKeys",
	HandlerType: (*APIKeysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminIssueAPIKey",
			Handler:    _APIKeys_AdminIssueAPIKey_Handler,
		},
		{
			MethodName: "AdminGetIssuedAPIKey",
			Handler:    _APIKeys_AdminGetIssuedAPIKey_Handler,
		},
		{
			MethodName: "AdminListIssuedAPIKeys",
			Handler:    _APIKeys_AdminListIssuedAPIKeys_Handler,
		},
		{
			MethodName: "AdminUpdateIssuedAPIKey",
			Handler:    _APIKeys_AdminUpdateIssuedAPIKey_Handler,
		},
		{
			MethodName: "AdminRotateIssuedAPIKey",
			Handler:    _APIKeys_AdminRotateIssuedAPIKey_Handler,
		},
		{
			MethodName: "AdminRevokeIssuedAPIKey",
			Handler:    _APIKeys_AdminRevokeIssuedAPIKey_Handler,
		},
		{
			MethodName: "AdminImportAPIKey",
			Handler:    _APIKeys_AdminImportAPIKey_Handler,
		},
		{
			MethodName: "AdminBatchImportAPIKeys",
			Handler:    _APIKeys_AdminBatchImportAPIKeys_Handler,
		},
		{
			MethodName: "AdminUpdateImportedAPIKey",
			Handler:    _APIKeys_AdminUpdateImportedAPIKey_Handler,
		},
		{
			MethodName: "AdminGetImportedAPIKey",
			Handler:    _APIKeys_AdminGetImportedAPIKey_Handler,
		},
		{
			MethodName: "AdminListImportedAPIKeys",
			Handler:    _APIKeys_AdminListImportedAPIKeys_Handler,
		},
		{
			MethodName: "AdminDeleteImportedAPIKey",
			Handler:    _APIKeys_AdminDeleteImportedAPIKey_Handler,
		},
		{
			MethodName: "AdminRevokeImportedAPIKey",
			Handler:    _APIKeys_AdminRevokeImportedAPIKey_Handler,
		},
		{
			MethodName: "RevokeAPIKey",
			Handler:    _APIKeys_RevokeAPIKey_Handler,
		},
		{
			MethodName: "AdminDeriveToken",
			Handler:    _APIKeys_AdminDeriveToken_Handler,
		},
		{
			MethodName: "GetJWKS",
			Handler:    _APIKeys_GetJWKS_Handler,
		},
		{
			MethodName: "AdminVerifyAPIKey",
			Handler:    _APIKeys_AdminVerifyAPIKey_Handler,
		},
		{
			MethodName: "AdminBatchVerifyAPIKeys",
			Handler:    _APIKeys_AdminBatchVerifyAPIKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/talos/v2alpha1/talos.proto",
}
